### ISSUE TITLE
Broken with activesupport 7: uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState

### ISSUE THREAD

**Issue by DannyBen** [weppos/whois-parser#141]
When activesupport 7 is installed, the gem breaks with this error:

### Error

```
/home/vagrant/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0
/lib/active_support/xml_mini.rb:184:in `current_thread_backend': uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState (NameError)
        from /home/vagrant/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:103:in `backend='
        from /home/vagrant/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:201:in `<module:ActiveSupport>'
        from /home/vagrant/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/xml_mini.rb:11:in `<top (required)>'
        # ...
```

### Reproduction

```ruby
require 'bundler/inline'

gemfile do
  source "https://rubygems.org"
  gem 'whois-parser'
  gem 'activesupport', '>= 7'   # FAIL
  # gem 'activesupport', '< 7'      # PASS
end

c = Whois::Client.new
p c.lookup("google.com")
```

**Comment by jarthod** [comment]
@DannyBen this gem is not maintained at the moment so after asking the maintainer I ended up starting [my fork](https://github.com/jarthod/whois-parser) in which I merged some of the pending PRs and provided a lot more fixes.
I fixed support for ActiveSupport 7 in 399fd2aebbf442682694c1f7ca66c8350c838967.
So you can use my fork in the meantime and hopefully one day we'll be able to merge upstream:

```ruby
gem 'whois-parser', github: 'jarthod/whois-parser' # Unofficial but more up-to-date fork, check status at https://github.com/jarthod/whois-parser
```

**Comment by DannyBen** [comment]
Thanks. Perhaps the maintainer can state this in the README.

**Comment by jarthod** [comment]
That would be nice yes, unfortunately we can't do it for him and he doesn't merge anything :confused:
