### ISSUE TITLE
Parsing .blog domains fails

### ISSUE THREAD

**Issue by OlliV** [weppos/whois-parser#40]
Getting the record with whois works ok but parser can't parse it.

```
irb(main):001:0> require 'whois-parser'
=> true
irb(main):002:0> record = Whois.whois("get.blog")
irb(main):003:0> parser = record.parser

irb(main):004:0> parser.nameservers
Whois::AttributeNotImplemented: Unable to find a parser for property `nameservers'
        from /usr/local/bundle/gems/whois-parser-1.0.0/lib/whois/parser.rb:350:in `delegate_property_o_parsers'
        from /usr/local/bundle/gems/whois-parser-1.0.0/lib/whois/parser.rb:312:in `nameservers'
        from /usr/local/bundle/gems/whois-parser-1.0.0/lib/whois/parser.rb:333:in `method_missing'
        from (irb):4
        from /usr/local/bin/irb:11:in `<main>'
```

**Comment by weppos** [comment]
That failure is actually an indicator that there is currently no parser available for the .BLOG tld. Feel free to provide a patch.
